### ISSUE TITLE
ROOT recommended libraries installation fails

### ISSUE THREAD

**Issue by LuckeeDev** [JustWhit3/useful-guides#7]
# Description
The ROOT installation guide for Ubuntu recommends installing some additional packages, but some of the installations fail.

> Other not mandatory, but recommended are:
> ```
> sudo apt install gfortran libssl-dev libpcre3-dev xlibmesa-glu-dev libglew1.5-dev libftgl-dev libmysqlclient-dev libfftw3-dev libcfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl0-dev
> ```

Here's the error I'm getting:
```
...
Note, selecting 'libglu1-mesa-dev' instead of 'xlibmesa-glu-dev'
Note, selecting 'libgraphviz-dev' instead of 'graphviz-dev'
Note, selecting 'libgsl-dev' instead of 'libgsl0-dev'
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-dev python2 python-dev-is-python3

E: Unable to locate package libglew1.5-dev
E: Couldn't find any package by glob 'libglew1.5-dev'
E: Package 'python-dev' has no installation candidate
...
```

## Context
Platform: Windows 11
WSL version: 2
Ubuntu version: 22.04.1 LTS

**Comment by JustWhit3** [comment]
Hi @LuckeeDev , thanks for the report.

These are optional libraries, so you don't have to worry about all of them for the correct installation of ROOT.

However, I fixed the libraries prerequisites list and now it should work. Basically, the `libglew1.5-dev` package is from Ubuntu 12 and probably is now deprecated, so I completely removed it. For what regards Python, I added `python2-dev` package (not Python 3) and this should be enough for the ROOT installation.

Cheers,
Gianluca.

**Comment by JustWhit3** [comment]
https://github.com/all-contributors please add @LuckeeDev for review

**Comment by JustWhit3** [comment]
@all-contributors please add @myermo for review

**Comment by JustWhit3** [comment]
@all-contributors please add @LuckeeDev for review
